weather_codes = [
    "Clear Night",
    "Sunny Day",
    "Sky unchanged",
    "Partly Cloudy",
    "Smoke haze",
    "Misty",
    "Foggy",
    "Cloudy",
    "Overcast",
    "Light Rain",
    "Mist",
    "Shallow fog patches",
    "Continuous shallow fog",
    "Lightning, no thunder",
    "Distant virga",
    "Distant precipitation",
    "Nearby precipitation",
    "Dry thunderstorm",
    "Squalls seen",
    "Funnel clouds seen",
    "Non-showery drizzle/snow",
    "Non-showery rain",
    "Non-showery snow",
    "Non-showery rain/snow",
    "Freezing drizzle/rain",
    "Rain showers",
    "Snow or mixed showers",
    "Hail showers",
    "Fog/ice fog",
    "Thunderstorm nearby",
    "Weak duststorm decreased",
    "Weak duststorm steady",
    "Weak duststorm rising",
    "Severe duststorm decreased",
    "Severe duststorm steady",
    "Severe duststorm rising",
    "Low drifting snow",
    "Heavy low snow drift",
    "High snow drift",
    "Heavy high snow drift",
    "Distant fog/ice fog",
    "Patchy fog/ice fog",
    "Fog thinning, sky visible",
    "Fog thinning, sky obscured",
    "Fog steady, sky visible",
    "Fog steady, sky obscured",
    "Fog thickening, sky visible",
    "Fog thickening, sky obscured",
    "Rime fog, visible sky",
    "Rime fog, obscured sky",
    "Light intermittent drizzle",
    "Light steady drizzle",
    "Moderate intermittent drizzle",
    "Moderate steady drizzle",
    "Heavy intermittent drizzle",
    "Heavy steady drizzle",
    "Freezing drizzle, light",
    "Freezing drizzle, moderate/heavy",
    "Light drizzle & rain",
    "Moderate/heavy drizzle & rain",
    "Light intermittent rain",
    "Light steady rain",
    "Moderate intermittent rain",
    "Moderate steady rain",
    "Heavy intermittent rain",
    "Heavy steady rain",
    "Freezing rain, light",
    "Freezing rain, moderate/heavy",
    "Light rain/snow",
    "Heavy rain/snow",
    "Light intermittent snow",
    "Light steady snow",
    "Moderate intermittent snow",
    "Moderate steady snow",
    "Heavy intermittent snow",
    "Heavy steady snow",
    "Diamond dust",
    "Snow grains",
    "Star-like crystals",
    "Ice pellets",
    "Light rain showers",
    "Moderate/heavy rain showers",
    "Violent rain showers",
    "Light rain/snow showers",
    "Heavy rain/snow showers",
    "Light snow showers",
    "Heavy snow showers",
    "Light snow pellets/hail",
    "Heavy snow pellets/hail",
    "Light hail, no thunder",
    "Heavy hail, no thunder",
    "Light rain now",
    "Heavy rain now",
    "Light snow/rain/hail",
    "Heavy snow/rain/hail",
    "Thunderstorm, light/moderate rain",
    "Thunderstorm with hail",
    "Heavy thunderstorm, no hail",
    "Thunderstorm + duststorm",
    "Thunderstorm + hail"
]
